### ISSUE TITLE
libc++abi.dylib: terminating with uncaught exception of type ecell4::NotFound: attribute

### ISSUE THREAD

**Issue by kozo2** [ecell/ecell4#130]
It seems when the users query non-existent key to `Species.get_attribute()` , this dylib terminates session.

If we can prevent this termination, we should do it.

**Comment by kaizu** [comment]
Do you mean?:

```
kaizu@tcs2:~/src/ecell4-develop$ python -c "from ecell4 import *; sp = Species('A'); print(sp.get_attribute('spam'))"
terminate called after throwing an instance of 'ecell4::NotFound'
  what():  attribute [spam] not found
Aborted
```

**Comment by kozo2** [comment]
Yes, that's what I mean

**Comment by kaizu** [comment]
```
kaizu@tcs2:~/src/ecell4-develop$ python -c "from ecell4 import *; sp = Species('A'); print(sp.get_attribute('spam'))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "lib/ecell4/Species.pxi", line 90, in ecell4.core.Species.get_attribute (lib/ecell4/core.cpp:5153)
RuntimeError: attribute [spam] not found
```

Now you can catch the exception on Python.
