### ISSUE TITLE
Species has boost::variant as its attribute

### ISSUE THREAD

**Issue by kaizu** [ecell/ecell4#196]
```python
with species_attributes():
    A | {'D': 0.1, 'radius': 0.005, 'location': 'membrane'}
```

**Comment by kaizu** [comment]
The above change only supports string or Real.
```python
>>> sp = Species("X")
>>> sp.set_attribute("spam", "ham")
>>> sp.set_attribute("eggs", 5)
>>> sp.get_attribute_as_variant("spam")
'ham'
>>> sp.get_attribute_as_variant("eggs")
5.0
>>> sp.get_attribute("spam")
'ham'
>>> sp.get_attribute("eggs")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "ecell4/Species.pxi", line 90, in ecell4.core.Species.get_attribute (/home/kaizu/src/ecell4-develop/python/lib/ecell4/core.cpp:5938)
RuntimeError: boost::bad_get: failed value get using boost::get
```

**Comment by kaizu** [comment]
```python
with species_attributes():
    A | {'D': 0.1, 'radius': 0.005, 'location': 'membrane'}

m = get_model()
A = m.species_attributes()[0]
print(A.serial(), A.list_attributes()) 
# => A [('radius', 0.005), ('D', 0.1), ('location', 'membrane')]
```

A Real value is recommended for 'D' and 'radius' though string is still accepted for the compatibility.
