### ISSUE TITLE
ImportError: DLL load failed:

### ISSUE THREAD

**Issue by kozo2** [ecell/ecell4#300]
## how to reproduce this error

I downloaded this whl from https://ci.appveyor.com/project/kozo2/ecell4/build/job/d92jse1vdf1rb27g/artifacts

```
PS C:\Users\a\Downloads> python -m pip install .\ecell-4.2.0-cp37-cp37m-win_amd64.whl
Processing c:\users\a\downloads\ecell-4.2.0-cp37-cp37m-win_amd64.whl
Installing collected packages: ecell
Successfully installed ecell-4.2.0
PS C:\Users\a\Downloads> python -m conda install hdf5=1.8.18
Solving environment: done

## Package Plan ##

  environment location: C:\Users\a\Miniconda3

  added / updated specs:
    - hdf5=1.8.18


The following NEW packages will be INSTALLED:

    hdf5: 1.8.18-hcf527f2_1

Proceed ([y]/n)?

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
PS C:\Users\a\Downloads> python
Python 3.7.0 (default, Jun 28 2018, 08:04:48) [MSC v.1912 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from ecell4 import core
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\a\Miniconda3\lib\site-packages\ecell4\__init__.py", line 1, in <module>
    from ecell4.core import *
ImportError: DLL load failed: 指定されたモジュールが見つかりません。
>>>
```

**Comment by kaizu** [comment]
I reproduced this issue. Let me check.

**Comment by kaizu** [comment]
https://github.com/Microsoft/vcpkg/blob/master/docs/users/triplets.md
https://github.com/Microsoft/vcpkg/blob/master/docs/users/integration.md
https://www.appveyor.com/docs/lang/cpp/
