### ISSUE TITLE
azure_batch.py fails with pickle FileNotFoundError

### ISSUE THREAD

**Issue by kozo2** [ecell/ecell4#323]
[azure_batch.py with my own parameters](https://gist.github.com/kozo2/91f56356c92d067057f9b318b42d017a) can not be executed successfully.

```

Your credentials class does not support session injection. Performance will not be at the maximum.
stderr.txt content for task topNtask2-4:
/bin/bash: line 1:  2687 Floating point exception(core dumped) python $AZ_BATCH_NODE_SHARED_DIR/task-7dfc757a.py --filepath input-7dfc757a_1.pickle --output output-7dfc757a_1.4.pickle --storageaccount ecell --task_id 2 --job_id 4 --storagecontainer output --sastoken "se=2019-02-05T22%3A38%3A14Z&sp=w&sv=2018-03-28&sr=c&sig=o26W9iKM17tvDzmledWv423lWSWatUyLw83fB%2BbkPG8%3D"

Your credentials class does not support session injection. Performance will not be at the maximum.
stdout.txt content for task topNtask2-5:

Your credentials class does not support session injection. Performance will not be at the maximum.
stderr.txt content for task topNtask2-5:
/bin/bash: line 1:  2560 Floating point exception(core dumped) python $AZ_BATCH_NODE_SHARED_DIR/task-7dfc757a.py --filepath input-7dfc757a_1.pickle --output output-7dfc757a_1.5.pickle --storageaccount ecell --task_id 2 --job_id 5 --storagecontainer output --sastoken "se=2019-02-05T22%3A38%3A14Z&sp=w&sv=2018-03-28&sr=c&sig=o26W9iKM17tvDzmledWv423lWSWatUyLw83fB%2BbkPG8%3D"

Your credentials class does not support session injection. Performance will not be at the maximum.
stdout.txt content for task topNtask2-6:

Your credentials class does not support session injection. Performance will not be at the maximum.
stderr.txt content for task topNtask2-6:
/bin/bash: line 1:  2647 Floating point exception(core dumped) python $AZ_BATCH_NODE_SHARED_DIR/task-7dfc757a.py --filepath input-7dfc757a_1.pickle --output output-7dfc757a_1.6.pickle --storageaccount ecell --task_id 2 --job_id 6 --storagecontainer output --sastoken "se=2019-02-05T22%3A38%3A14Z&sp=w&sv=2018-03-28&sr=c&sig=o26W9iKM17tvDzmledWv423lWSWatUyLw83fB%2BbkPG8%3D"

Your credentials class does not support session injection. Performance will not be at the maximum.
stdout.txt content for task topNtask2-7:

Your credentials class does not support session injection. Performance will not be at the maximum.
stderr.txt content for task topNtask2-7:
/bin/bash: line 1:  2627 Floating point exception(core dumped) python $AZ_BATCH_NODE_SHARED_DIR/task-7dfc757a.py --filepath input-7dfc757a_1.pickle --output output-7dfc757a_1.7.pickle --storageaccount ecell --task_id 2 --job_id 7 --storagecontainer output --sastoken "se=2019-02-05T22%3A38%3A14Z&sp=w&sv=2018-03-28&sr=c&sig=o26W9iKM17tvDzmledWv423lWSWatUyLw83fB%2BbkPG8%3D"

Your credentials class does not support session injection. Performance will not be at the maximum.
stdout.txt content for task topNtask2-8:

Your credentials class does not support session injection. Performance will not be at the maximum.
stderr.txt content for task topNtask2-8:
/bin/bash: line 1:  2572 Floating point exception(core dumped) python $AZ_BATCH_NODE_SHARED_DIR/task-7dfc757a.py --filepath input-7dfc757a_1.pickle --output output-7dfc757a_1.8.pickle --storageaccount ecell --task_id 2 --job_id 8 --storagecontainer output --sastoken "se=2019-02-05T22%3A38%3A14Z&sp=w&sv=2018-03-28&sr=c&sig=o26W9iKM17tvDzmledWv423lWSWatUyLw83fB%2BbkPG8%3D"

Your credentials class does not support session injection. Performance will not be at the maximum.
stdout.txt content for task topNtask2-9:

Your credentials class does not support session injection. Performance will not be at the maximum.
stderr.txt content for task topNtask2-9:
/bin/bash: line 1:  2541 Floating point exception(core dumped) python $AZ_BATCH_NODE_SHARED_DIR/task-7dfc757a.py --filepath input-7dfc757a_1.pickle --output output-7dfc757a_1.9.pickle --storageaccount ecell --task_id 2 --job_id 9 --storagecontainer output --sastoken "se=2019-02-05T22%3A38%3A14Z&sp=w&sv=2018-03-28&sr=c&sig=o26W9iKM17tvDzmledWv423lWSWatUyLw83fB%2BbkPG8%3D"

Your credentials class does not support session injection. Performance will not be at the maximum.
stdout.txt content for task topNtask2-10:

Your credentials class does not support session injection. Performance will not be at the maximum.
stderr.txt content for task topNtask2-10:
/bin/bash: line 1:  2671 Floating point exception(core dumped) python $AZ_BATCH_NODE_SHARED_DIR/task-7dfc757a.py --filepath input-7dfc757a_1.pickle --output output-7dfc757a_1.10.pickle --storageaccount ecell --task_id 2 --job_id 10 --storagecontainer output --sastoken "se=2019-02-05T22%3A38%3A14Z&sp=w&sv=2018-03-28&sr=c&sig=o26W9iKM17tvDzmledWv423lWSWatUyLw83fB%2BbkPG8%3D"

Sample end: 2019-02-06 05:41:17
Elapsed time: 0:03:04
Deleting containers...
Deleting job [MyJob-7dfc757a-1] ...
Your credentials class does not support session injection. Performance will not be at the maximum.
Deleting pool...
Your credentials class does not support session injection. Performance will not be at the maximum.
Deleting temporary files...
Traceback (most recent call last):
  File ".\azure_batch.py", line 778, in <module>
    res = run_azure(singlerun, jobs, n=10, path='tmp', config='example.ini')
  File ".\azure_batch.py", line 717, in run_azure
    with open(os.path.join(path, output_file), mode='rb') as fin:
FileNotFoundError: [Errno 2] No such file or directory: 'tmp\\output-7dfc757a_0.1.pickle'
(base) PS C:\Users\a>

```

**Comment by kaizu** [comment]
The messages tell us that this issue is not about pickling. See below:

```
/bin/bash: line 1:  2541 Floating point exception(core dumped) python $AZ_BATCH_NODE_SHARED_DIR/task-7dfc757a.py --filepath input-7dfc757a_1.pickle --output output-7dfc757a_1.9.pickle ...
```

Azure failed to run simulations and to generate the results pickled. But I'm not sure why it failed. Please check if the task properly works in the serial way.
